### ISSUE TITLE
最新版

### ISSUE THREAD

**Issue by ziimee** [admpub/nging#405]
[Register Extend Config] P25104 wanIPProvider: *ip2region.WANIPProviders
[ INFO]25104|2021-11-29 21:42:10|Info|app|Currently running in debug mode

         SYSTEM MONITOR         
                                
 Starting collect server status 
                                
            POWERED BY WEBX.TOP 

panic: Not connected to any database

goroutine 28 [running]:
github.com/webx-top/db/lib/factory.(*Factory).Cluster(0xc00094bd08, 0x452974)
	/source/vendor/github.com/webx-top/db/lib/factory/factory.go:154 +0x65
github.com/webx-top/db/lib/factory.(*Transaction).Database(0xc000149f00, 0xc000538140)
	/source/vendor/github.com/webx-top/db/lib/factory/transaction.go:21 +0x65
github.com/webx-top/db/lib/factory.(*Transaction).C(0xc000650060, 0xc000538140)
	/source/vendor/github.com/webx-top/db/lib/factory/transaction.go:74 +0x25
github.com/webx-top/db/lib/factory.(*Transaction).result(0x251fa60, 0xc000538140)
	/source/vendor/github.com/webx-top/db/lib/factory/transaction.go:58 +0x25
github.com/webx-top/db/lib/factory.(*Transaction).Result(0x30b3fd6, 0xc000538140)
	/source/vendor/github.com/webx-top/db/lib/factory/transaction.go:66 +0x1e
github.com/webx-top/db/lib/factory.(*Transaction).List(0xc000149f00, 0xc000538140)
	/source/vendor/github.com/webx-top/db/lib/factory/transaction.go:247 +0x106
github.com/webx-top/db/lib/factory.(*Param).List(0xc0007f60b0)
	/source/vendor/github.com/webx-top/db/lib/factory/param.go:590 +0x37
github.com/admpub/nging/v3/application/dbschema.(*NgingFrpServer).ListByOffset(0xc00000c780, {0x0, 0x0}, 0xf, 0x0, 0xffffffffffffffff, {0xc0007f6100, 0x7, 0x0})
	/source/application/dbschema/NgingFrpServer.go:329 +0x1d3
github.com/admpub/nging/v3/application/handler/frp/plugins/multiuser.OnChangeBackendURL({0x31a5178, 0xc00000c5a0})
	/source/application/handler/frp/plugins/multiuser/multiuser.go:66 +0x2d2
github.com/admpub/nging/v3/application/handler/frp/plugins/multiuser.init.0.func2.1()
	/source/application/handler/frp/plugins/multiuser/init.go:46 +0x2c
created by github.com/admpub/nging/v3/application/handler/frp/plugins/multiuser.init.0.func2
	/source/application/handler/frp/plugins/multiuser/init.go:44 +0x6b

**Comment by admpub** [comment]
说明数据库连接失败。可以检查配置文件config/config.yaml内的数据库账号配置是否正确

**Comment by ziimee** [comment]
好，我看下，开始不支持 sqllite？原来版本执行后，就默认启动，访问9999，进入安装

**Comment by admpub** [comment]
如果是重新安装需要删除程序根目录下的installed.lock文件

**Comment by admpub** [comment]
一直支持sqlite的

**Comment by admpub** [comment]
我这里复现了，确认是一个bug，我修复一下

**Comment by admpub** [comment]
已解决 v3.6.4
